using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using SmartSure.AdminService.Data;
using SmartSure.AdminService.DTOs;
using SmartSure.AdminService.Models;
using System.Text.Json;

namespace SmartSure.AdminService.Services
{
    public class ReportService : IReportService
    {
        private readonly AdminDbContext _context;
        private readonly ILogger<ReportService> _logger;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;

        public ReportService(AdminDbContext context, ILogger<ReportService> logger, IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _context = context;
            _logger = logger;
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
        }

        public async Task<ReportResponseDTO> GenerateReportAsync(Guid adminId, ReportRequestDTO dto, string token)
        {
            // Generate report content based on type
            var content = await GenerateContentAsync(dto, token);

            var report = new Report
            {
                ReportId = Guid.NewGuid(),
                Title = dto.Title,
                ReportType = dto.ReportType,
                Format = dto.Format,
                Content = content,
                GeneratedBy = adminId,
                DateRangeStart = dto.DateRangeStart,
                DateRangeEnd = dto.DateRangeEnd
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();

            _logger.LogInformation("Report {ReportId} generated by admin {AdminId}: {Title}", report.ReportId, adminId, dto.Title);

            return MapToDto(report);
        }

        public async Task<List<ReportResponseDTO>> GetReportsAsync()
        {
            var reports = await _context.Reports
                .OrderByDescending(r => r.CreatedAt)
                .ToListAsync();

            return reports.Select(MapToDto).ToList();
        }

        public async Task<ReportResponseDTO?> GetReportByIdAsync(Guid reportId)
        {
            var report = await _context.Reports.FindAsync(reportId);
            return report == null ? null : MapToDto(report);
        }

        private async Task<string> GenerateContentAsync(ReportRequestDTO dto, string token)
        {
            // Generate JSON payload based on report type
            // In production this would query policy/claims data via HTTP or shared DB views
            var gatewayUrl = _configuration["Gateway:Url"] ?? "http://localhost:5057";
            var client = _httpClientFactory.CreateClient();
            
            // Remove "Bearer " prefix if it exists and add it back properly
            var cleanToken = token.Replace("Bearer ", "").Trim();
            client.DefaultRequestHeaders.Add("Authorization", $"Bearer {cleanToken}");

            int totalInsuranceSell = 0;
            int totalClaimAccepted = 0;
            int totalClaimRejected = 0;

            try
            {
                _logger.LogInformation("Fetching policies from {Url}", $"{gatewayUrl}/policies/all");
                var policiesResponse = await client.GetAsync($"{gatewayUrl}/policies/all");
                _logger.LogInformation("Policies response status: {Status}", policiesResponse.StatusCode);
                
                if (policiesResponse.IsSuccessStatusCode)
                {
                    var policiesStr = await policiesResponse.Content.ReadAsStringAsync();
                    var policies = JsonSerializer.Deserialize<JsonElement[]>(policiesStr);
                    if (policies != null)
                    {
                        totalInsuranceSell = policies.Length;
                    }
                }
                else
                {
                    var errorContent = await policiesResponse.Content.ReadAsStringAsync();
                    _logger.LogWarning("Failed to fetch policies: {Status} - {Content}", policiesResponse.StatusCode, errorContent);
                }

                _logger.LogInformation("Fetching claims from {Url}", $"{gatewayUrl}/claims/all");
                var claimsResponse = await client.GetAsync($"{gatewayUrl}/claims/all");
                _logger.LogInformation("Claims response status: {Status}", claimsResponse.StatusCode);
                
                if (claimsResponse.IsSuccessStatusCode)
                {
                    var claimsStr = await claimsResponse.Content.ReadAsStringAsync();
                    var claims = JsonSerializer.Deserialize<JsonElement[]>(claimsStr);
                    if (claims != null)
                    {
                        totalClaimAccepted = claims.Count(c => c.TryGetProperty("status", out var s) && s.GetString() == "Approved");
                        totalClaimRejected = claims.Count(c => c.TryGetProperty("status", out var s) && s.GetString() == "Rejected");
                    }
                }
                else
                {
                    var errorContent = await claimsResponse.Content.ReadAsStringAsync();
                    _logger.LogWarning("Failed to fetch claims: {Status} - {Content}", claimsResponse.StatusCode, errorContent);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching data for report generation");
                throw; // Re-throw to let the controller handle it
            }

            var reportData = new
            {
                title = dto.Title,
                type = dto.ReportType,
                dateRange = new { start = dto.DateRangeStart, end = dto.DateRangeEnd },
                generatedAt = DateTime.UtcNow,
                summary = $"Report generated for {dto.ReportType} from {dto.DateRangeStart:yyyy-MM-dd} to {dto.DateRangeEnd:yyyy-MM-dd}",
                statistics = new {
                    totalInsuranceSell,
                    totalClaimAccepted,
                    totalClaimRejected
                }
            };

            return JsonSerializer.Serialize(reportData);
        }

        private static ReportResponseDTO MapToDto(Report report)
        {
            return new ReportResponseDTO
            {
                ReportId = report.ReportId,
                Title = report.Title,
                ReportType = report.ReportType,
                Format = report.Format,
                Content = report.Content,
                GeneratedBy = report.GeneratedBy,
                DateRangeStart = report.DateRangeStart,
                DateRangeEnd = report.DateRangeEnd,
                CreatedAt = report.CreatedAt
            };
        }
    }
}
