using Microsoft.EntityFrameworkCore;
using SmartSure.AdminService.Data;
using SmartSure.AdminService.DTOs;
using SmartSure.AdminService.Models;
using System.Text.Json;

namespace SmartSure.AdminService.Services
{
    public class ReportService : IReportService
    {
        private readonly AdminDbContext _context;
        private readonly ILogger<ReportService> _logger;

        public ReportService(AdminDbContext context, ILogger<ReportService> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<ReportResponseDTO> GenerateReportAsync(Guid adminId, ReportRequestDTO dto)
        {
            // Generate report content based on type
            var content = await GenerateContentAsync(dto);

            var report = new Report
            {
                ReportId = Guid.NewGuid(),
                Title = dto.Title,
                ReportType = dto.ReportType,
                Format = dto.Format,
                Content = content,
                GeneratedBy = adminId,
                DateRangeStart = dto.DateRangeStart,
                DateRangeEnd = dto.DateRangeEnd
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();

            _logger.LogInformation("Report {ReportId} generated by admin {AdminId}: {Title}", report.ReportId, adminId, dto.Title);

            return MapToDto(report);
        }

        public async Task<List<ReportResponseDTO>> GetReportsAsync()
        {
            var reports = await _context.Reports
                .OrderByDescending(r => r.CreatedAt)
                .ToListAsync();

            return reports.Select(MapToDto).ToList();
        }

        public async Task<ReportResponseDTO?> GetReportByIdAsync(Guid reportId)
        {
            var report = await _context.Reports.FindAsync(reportId);
            return report == null ? null : MapToDto(report);
        }

        private async Task<string> GenerateContentAsync(ReportRequestDTO dto)
        {
            // Generate JSON payload based on report type
            // In production this would query policy/claims data via HTTP or shared DB views
            var reportData = new
            {
                title = dto.Title,
                type = dto.ReportType,
                dateRange = new { start = dto.DateRangeStart, end = dto.DateRangeEnd },
                generatedAt = DateTime.UtcNow,
                summary = $"Report generated for {dto.ReportType} from {dto.DateRangeStart:yyyy-MM-dd} to {dto.DateRangeEnd:yyyy-MM-dd}"
            };

            return JsonSerializer.Serialize(reportData);
        }

        private static ReportResponseDTO MapToDto(Report report)
        {
            return new ReportResponseDTO
            {
                ReportId = report.ReportId,
                Title = report.Title,
                ReportType = report.ReportType,
                Format = report.Format,
                Content = report.Content,
                GeneratedBy = report.GeneratedBy,
                DateRangeStart = report.DateRangeStart,
                DateRangeEnd = report.DateRangeEnd,
                CreatedAt = report.CreatedAt
            };
        }
    }
}
